### ISSUE TITLE
Compilation Errors: marked 'override', but does not override in multiple functions

### ISSUE THREAD

**Issue by aaronbeckmann** [TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper#14] opened 2024-02-08 16:32 UTC
First of all thank you for your ESPHome wrapper for HUB75 displays. You've built exactly what I am looking for! I sadly have an issue with the compilation in esphome. I don't know if I have something misconfigured. 

ESPHome Version is 2023.11.6.

Cleaning Build Files did not resolve the issue.

### Issue:
Compilation Errors: marked 'override', but does not override in multiple functions

### ESPHome Yaml File

```esphome:
  name: hub75display
  friendly_name: hub75display

external_components:
  - source: github://TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper@main

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

<wifi stuff here> 

font:
  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto
    size: 10

display:
  - platform: hub75_matrix_display
    id: matrix
    width: 64
    height: 64
    update_interval: 16 ms
    R1_pin: 2
    G1_pin: 3
    B1_pin: 4
    R2_pin: 5
    G2_pin: 8
    B2_pin: 9
    A_pin: 10
    CLK_pin: 11
    LAT_pin: 12
    OE_pin: 13
    B_pin: 16
    C_pin: 18
    D_pin: 20
    E_pin: 19
    lambda: |-
      it.print(0, 0, id(roboto), "Hello World!");

switch:
  - platform: hub75_matrix_display
    matrix_id: matrix
    name: "Power"
    id: power

number:
  - platform: hub75_matrix_display
    matrix_id: matrix
    name: "Brightness"
```

### Logs:

```Compiling .pioenvs/hub75display/src/esphome/components/font/font.cpp.o
Compiling .pioenvs/hub75display/src/esphome/components/hub75_matrix_display/matrix_display.cpp.o
Compiling .pioenvs/hub75display/src/esphome/components/hub75_matrix_display/number/matrix_display_brightness.cpp.o
In file included from src/esphome/components/hub75_matrix_display/matrix_display.cpp:1:
src/esphome/components/hub75_matrix_display/matrix_display.h:32:18: error: 'void esphome::matrix_display::MatrixDisplay::setup()' marked 'override', but does not override
             void setup() override;
                  ^~~~~
src/esphome/components/hub75_matrix_display/matrix_display.h:34:18: error: 'void esphome::matrix_display::MatrixDisplay::dump_config()' marked 'override', but does not override
             void dump_config() override;
                  ^~~~~~~~~~~
src/esphome/components/hub75_matrix_display/matrix_display.h:36:18: error: 'void esphome::matrix_display::MatrixDisplay::update()' marked 'override', but does not override
             void update() override;
                  ^~~~~~
src/esphome/components/hub75_matrix_display/matrix_display.cpp: In member function 'void esphome::matrix_display::MatrixDisplay::setup()':
src/esphome/components/hub75_matrix_display/matrix_display.cpp:36:48: error: 'update_interval_' was not declared in this scope
             mxconfig.min_refresh_rate = 1000 / update_interval_;
                                                ^~~~~~~~~~~~~~~~
src/esphome/components/hub75_matrix_display/matrix_display.cpp:36:48: note: suggested alternative: 'init_internal_'
             mxconfig.min_refresh_rate = 1000 / update_interval_;
                                                ^~~~~~~~~~~~~~~~
                                                init_internal_
*** [.pioenvs/hub75display/src/esphome/components/hub75_matrix_display/matrix_display.cpp.o] Error 1
In file included from src/esphome/components/hub75_matrix_display/number/matrix_display_brightness.h:5,
                 from src/esphome/components/hub75_matrix_display/number/matrix_display_brightness.cpp:1:
src/esphome/components/hub75_matrix_display/number/../matrix_display.h:32:18: error: 'void esphome::matrix_display::MatrixDisplay::setup()' marked 'override', but does not override
             void setup() override;
                  ^~~~~
src/esphome/components/hub75_matrix_display/number/../matrix_display.h:34:18: error: 'void esphome::matrix_display::MatrixDisplay::dump_config()' marked 'override', but does not override
             void dump_config() override;
                  ^~~~~~~~~~~
src/esphome/components/hub75_matrix_display/number/../matrix_display.h:36:18: error: 'void esphome::matrix_display::MatrixDisplay::update()' marked 'override', but does not override
             void update() override;
                  ^~~~~~
*** [.pioenvs/hub75display/src/esphome/components/hub75_matrix_display/number/matrix_display_brightness.cpp.o] Error 1
========================== [FAILED] Took 8.13 seconds ==========================```

**Comment by TillFleisch** [comment] 2024-02-08 18:27
Duplicate of #10

**Closed by TillFleisch** 2024-02-08 18:27 UTC
